server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index VOIS_EG_Summer_Service_V0__.html;

    location / {
        try_files $uri $uri/ /VOIS_EG_Summer_Service_V0__.html;
    }

    # Enable gzip for faster load
    gzip on;
    gzip_types text/html text/css application/javascript;
}